### ISSUE TITLE
Objects arent being parsed in

### ISSUE THREAD

**Issue by Altenhh** [gd-edit/GDAPI#19]
When trying to create a new level with an already premade Level string, the objects are not being parsed. while the level string is loaded in it still doesn't parse into separate object classes, could be something to do with missing to call a function?

**Comment by AlFasGD** [comment]
This is probably fixed, please test and close if fixed.

**Comment by Altenhh** [comment]
I have just tested in `for the first time since fucking forever` and it seems to have been fixed after putting `InitializeLoadingLevelString`!
![image](https://alten.s-ul.eu/Ku2HgFwg.png)
